INSERT INTO maps (owner_id, title, description, is_public)
VALUES
(1, 'Adams Map1', 'SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH', true),
(1, 'Adams Map2', 'SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH', true),
(1, 'Adams Secret Map', 'SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH', false),
(2, 'Leons Map1', 'SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH', true),
(2, 'Leons Map2', 'SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH', true),
(2, 'Leons Secret Map', 'SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH', false),
(3, 'Josephs Map1', 'SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH', true),
(3, 'Josephs Map2', 'SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH', true),
(3, 'Josephs Secret Map', 'SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH', false);
