DROP TABLE IF EXISTS pins CASCADE;
CREATE TABLE pins (
  id SERIAL PRIMARY KEY NOT NULL,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  long DECIMAL NOT NULL,
  lat DECIMAL NOT NULL,
  icon VARCHAR(255) NOT NULL,
  description TEXT NOT NULL
);
